// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1LN0Pqhr9c1H_AlapChSpVlwNqdhBhA',
    appId: '1:22712280427:web:d62b4d7ac7ac19c2b3582e',
    messagingSenderId: '22712280427',
    projectId: 'testing-61518',
    authDomain: 'testing-61518.firebaseapp.com',
    storageBucket: 'testing-61518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVF6ElinIrHy-GYxzzApXl-rmnJd8B5YU',
    appId: '1:22712280427:android:971f63f870a212dcb3582e',
    messagingSenderId: '22712280427',
    projectId: 'testing-61518',
    storageBucket: 'testing-61518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHzVmnfEA5zN0LZRNr13SsnXlRQGW7G0',
    appId: '1:22712280427:ios:074cc94fa732adeeb3582e',
    messagingSenderId: '22712280427',
    projectId: 'testing-61518',
    storageBucket: 'testing-61518.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrHzVmnfEA5zN0LZRNr13SsnXlRQGW7G0',
    appId: '1:22712280427:ios:576d71a612cb9063b3582e',
    messagingSenderId: '22712280427',
    projectId: 'testing-61518',
    storageBucket: 'testing-61518.appspot.com',
    iosBundleId: 'com.example.myFirstApp.RunnerTests',
  );
}
